FROM golang:1.21

WORKDIR $GOPATH/src/cos518project/
COPY . .

# Dependencies
RUN go mod init cos518project && go mod tidy

# Build executable
RUN go build -o bin/simple_client chubby/cmd/simple_client.go

# Run simple_client exec
CMD ["bin/simple_client"]
