FROM golang:1.21

WORKDIR $GOPATH/src/cos518project/
COPY . .

# Dependencies
RUN go mod init cos518project && go mod tidy

# Build executable
RUN go build -o chubby/acquire_lock_client chubby/cmd/acquire_Lock_Client.go

# Run simple_client exec
CMD ["chubby/acquire_lock_client"]
