FROM golang:1.21

WORKDIR $GOPATH/src/cos518project/
COPY . .

# Dependencies
RUN go mod init cos518project && go mod tidy

# Build executable
RUN go build -o bin/chubby chubby/cmd/main.go

# Run chubby exec
CMD ["bin/chubby", "-id", "node2", "-listen", "172.20.128.2:5379", "-raftbind", "172.20.128.2:15379", "-join", "172.20.128.1:5379"]