FROM golang:1.21

WORKDIR $GOPATH/src/cos518project/
COPY . .

# Dependencies
RUN go mod init cos518project && go mod tidy

# Build executable
RUN go build -o bin/task_queue chubby/cmd/task_queue.go

# Default CMD (overridden by docker-compose args)
ARG MODE=worker
ARG ID=1
CMD bin/task_queue -mode $MODE -id $ID
