version: '3'
services:
    node1:
        build:
            context: .
            dockerfile: Dockerfile.node1
        networks:
            static-network:
                ipv4_address: 172.20.128.1
    node2:
        build:
            context: .
            dockerfile: Dockerfile.node2
        restart: on-failure
        depends_on:
            - "node1"
        networks:
            static-network:
                ipv4_address: 172.20.128.2
    node3:
        build:
            context: .
            dockerfile: Dockerfile.node3
        restart: on-failure
        depends_on:
            - "node1"
        networks:
            static-network:
                ipv4_address: 172.20.128.3
    node4:
        build:
            context: .
            dockerfile: Dockerfile.node4
        restart: on-failure
        depends_on:
            - "node1"
        networks:
            static-network:
                ipv4_address: 172.20.128.4
    node5:
        build:
            context: .
            dockerfile: Dockerfile.node5
        restart: on-failure
        depends_on:
            - "node1"
        networks:
            static-network:
                ipv4_address: 172.20.128.5
    task_producer:
        build:
            context: .
            dockerfile: Dockerfile.taskqueue
        environment:
            - MODE=producer
            - ID=0
        restart: "no"
        depends_on:
            - "node1"
            - "node2"
            - "node3"
            - "node4"
            - "node5"
        networks:
            static-network:
              ipv4_address: 172.20.128.10

    task_worker1:
        build:
            context: .
            dockerfile: Dockerfile.taskqueue
        environment:
            - MODE=worker
            - ID=1
        restart: "no"
        depends_on:
            - "node1"
            - "node2"
            - "node3"
            - "node4"
            - "node5"
        networks:
            static-network:
                ipv4_address: 172.20.128.11
    task_worker2:
        build:
            context: .
            dockerfile: Dockerfile.taskqueue
        environment:
            - MODE=worker
            - ID=2
        restart: "no"
        depends_on:
            - "node1"
            - "node2"
            - "node3"
            - "node4"
            - "node5"
        networks:
            static-network:
                ipv4_address: 172.20.128.12
    task_worker3:
        build:
            context: .
            dockerfile: Dockerfile.taskqueue
        environment:
            - MODE=worker
            - ID=3
        restart: "no"
        depends_on:
            - "node1"
            - "node2"
            - "node3"
            - "node4"
            - "node5"
        networks:
            static-network:
                ipv4_address: 172.20.128.13
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16